export const styles = {
    container: {
      maxWidth: '75%',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      fontFamily: 'Arial, sans-serif',
      width: '100%',
      height: '100vh',
      padding: '20px',
      boxSizing: 'border-box',
    },
    header: {
      display: 'flex',
      justifyContent: 'space-between',
      width: '100%',
      marginBottom: '20px',
    },
    input: {
      padding: '10px',
      fontSize: '16px',
      width: '100%',
      marginBottom: '10px',
      boxSizing: 'border-box',
    },
    button: {
      padding: '10px',
      fontSize: '16px',
      cursor: 'pointer',
      marginTop: '10px',
    },
    svgContainer: {
      border: '1px solid #ccc',
      minHeight: '500px',
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      marginTop: '10px',
      overflow: 'auto',
      background: '#80808038',
      position: 'relative',
    },
    parametersUrlContainer: {
      width: '100%',
      marginTop: '10px',
    },
    parametersUrlLabelArea: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    parametersUrlTextarea: {
      width: '100%',
      minHeight: '80px',
      fontFamily: 'monospace',
      fontSize: '14px',
      boxSizing: 'border-box',
    },
    metricsContainer: {
      marginTop: '10px',
      padding: '10px',
      border: '1px solid #ddd',
      width: '100%',
      textAlign: 'center',
    },
    averageText: { color: 'red', fontWeight: 'bold' },
    gCodeContainer: {
      width: '100%',
      marginTop: '10px',
    },
    gCodeTextArea: {
      width: '100%',
      minHeight: '100px',
      fontFamily: 'monospace',
      fontSize: '12px',
      boxSizing: 'border-box',
    },
  }
  